### ISSUE TITLE
[Support] Can't get it to work

### ISSUE THREAD

**Issue by sinanozdemir** [knassar702/scant3r#12]
Hello,

I am trying to run scant3r in a lab, but it is failing to find valid SQLi's. On the other hand, wapiti finds all the injection points. Here is an example:

`echo 'http://sql1.webapp.site/newsdetails.php?id=26' | ./scant3r.py -m headers`
![image](https://user-images.githubusercontent.com/36063091/101674428-7ae61780-3a26-11eb-88bc-a00b559076cb.png)

I already ran `pip3 install -r requirements.txt` Can you give me some directions?
Again, wapiti identifies the SQLi point on this url, but scant3r fails.

Thanks

**Comment by knassar702** [comment]
hi @sinanozdemir 
`./scant3r.py -m headers` : for scanning headers not parameters , if you need to scan custom header you can add it in `modules/headers.py` file
```python
SCAN_Headers = [
    'User-agent',
    'referer',
    'Example'
    ] # add you headers here
```

you can use `-S` option for scan all parameters after the modules ends its work
```bash
$ echo 'http://testphp.vulnweb.com/search.php?test=query' | ./scant3r.py -m headers -S
```

best regards :heart: 

@knassar702

**Comment by sinanozdemir** [comment]
Thank you for your response, but adding the below headers still didn't return a valid SQL injection result:
Here are the headers:
![image](https://user-images.githubusercontent.com/36063091/101680879-55114080-3a2f-11eb-9ca6-26faa3ca960a.png)

I added a few of them to the headers.py:
![image](https://user-images.githubusercontent.com/36063091/101680958-6c502e00-3a2f-11eb-8399-403a3ddf2d2d.png)

`echo 'http://sql1.webapp.site/newsdetails.php?id=26' | ./scant3r.py -m headers -S` still nothing:
![image](https://user-images.githubusercontent.com/36063091/101681035-8db11a00-3a2f-11eb-9926-c933844f1e24.png)

I am not sure what's going on here.

Thanks

**Comment by knassar702** [comment]
hi @sinanozdemir 

if you add something like `' " \` in the parameter/headers do you get an sql error message in the response ?
***
If the answer is no, then this is not vulnerable for scant3r , because scant3r add `" '` for get SQL error like `syntax error | mysql_error | etc ..` , If the response includes this error, it will print that it is vulnerable
https://github.com/knassar702/scant3r/blob/master/wordlists/make_payload.py#L22

In this case, this is blind sql injection
you scan use [SQLMAP](https://github.com/sqlmapproject/sqlmap) project or scan it manually for example try to execute `sleep(5)` function or something like that :smiley:

### Some resources can help you 
* [OWASP SQLI](https://owasp.org/www-community/attacks/SQL_Injection)
* [SQLMAP tamper scripts](https://forum.bugcrowd.com/t/sqlmap-tamper-scripts-sql-injection-and-waf-bypass/423)
* [SQLI payloads](https://github.com/payloadbox/sql-injection-payload-list)
* [Computerphile - SQLI](https://www.youtube.com/watch?v=ciNHn38EyRc)

best regards :heart: 

@knassar702

**Comment by sinanozdemir** [comment]
Thank you for response again.
I see what you are saying now. It makes sense.

Thank you for help.
