### ISSUE TITLE
[BUG] scant3r doesn't start

### ISSUE THREAD

**Issue by Lucas01120** [knassar702/scant3r#16]
**Describe the bug**
I have installed scant3r on different platforms (kali, windows, ubuntu..) and every time I try to run the script it does not start. It only shows me the beginning.

**To Reproduce**
the commands I tried to run :
echo "my-website.com" | ./scant3r
echo "my-website.com" | python3 scant3r
echo "my-website.com" | python3.9 scant3r
etc..

**Screenshots**
![image](https://user-images.githubusercontent.com/37264718/111759199-a5553580-889d-11eb-9686-52484b259356.png)

**Desktop :**
 - OS: Kali-Linux 2021, Ubuntu for Windows.
 - Compiler Python
 - Version 3.9.1

**Comment by knassar702** [comment]
hello @Lucas01120 
This is because you are using the latest version , in 0.7 version you need to select the module who you want to work

https://github.com/knassar702/scant3r/wiki/Usage
```bash
$ echo "http://testphp.vulnweb.com/search.php?test=query&searchFor=1&goButton=go" | python3 scant3r.py -m xss

[XSS] Found :> http://testphp.vulnweb.com/search.php
	[!] Method: POST
	[!] Params: test=query&searchFor=1">ScanT3r<svg/onload=confirm(/ScanT3r/)>web"&goButton=go
```

The new version is ready (0.7), but it needs more modules (`sqli,rce,ssrf etc ..`), so you can use 0.6 version for more scan (`sqli xss rce ssti and some modules`) 

you can download it from here: https://github.com/knassar702/scant3r/releases/tag/0.6

for start 
```bash
$ echo "http://testphp.vulnweb.com/search.php?test=query&searchFor=1&goButton=go" | ./scant3r.py
```

king regards
@knassar702
