### ISSUE TITLE
Module Methods

### ISSUE THREAD

**Issue by MariusVinaschi** [knassar702/scant3r#31]
Hi, how are you? 

I have found some strange things in the module and I can't say if it's correct. 
1. SQLI 

In the folder _/modules/sqli/_. The start method in Sqli class always returns an empty dictionary.  After that, we compare the c value in the file _/modules/sqli/__init__.py_. 

```python
def main(opts, http):
    c = Sqli(opts, http).start()
    # C is always an empty dict
    if c:
        return c 
```
2. Reflect 

In both file _/modules/reflect/__init.__.py/_ and _/modules/reflect/reflect.py_ there is a check on the URLs. I think only one check may be sufficient. 

```python
if urlparse(opts['url']).query: 
    pass 
```

3. RCE 

In the start method in the file _/modules/rce/rec.py_ I don't understand why we only return the first payload. 

```python
if match in dump_response(r):
    return {
        'payload':payload.replace('\n','%0a').replace('\t','%0d'),
        'match':match,
        'http':r
    }
``` 

4. SSRF and SSTI 

I don't understand why in the 'GET' method we send the request to n and in the 'POST' we send the request to the _self.opts['url']_. 

```python
for n in nurl:
  if method == 'GET':
      r = self.http.send(method,n)
  else:
      r = self.http.send(method, self.opts['url'].split('?')[0], body=urlparse(n).query)
```

Thank you in advance for your answers. 
Best regards 
Marius

**Comment by knassar702** [comment]
hello @MariusVinaschi , 

> SQLI

Because of the updates and tests of new features in my head , the code/logic has changed and I always forget to delete those lines after test :laughing:

> SSTI

in post method we send the request without parameters in url , But I should have used `n` instead of `opts['url']`


> RCE 

yeah it should changed to better output

finally i don't update the modules from a long time , i code this modules in a hurry idk why , so this the time for update them and add more modules :D 

Thanks for letting me know this :heart:
best regards @knassar702

**Comment by MariusVinaschi** [comment]
I made some modification in my last pull request to resolve some of this problem. 

Best regards 
Marius
